apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: subscription
  description: The Petstore is an example API used to show features of the OpenAPI spec.
  annotations:
    backstage.io/techdocs-ref: url:https://dev.azure.com/rtl-nl/RTL%20Shared/_git/documentation
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-api
  description: Retrieve petstore details
spec:
  type: openapi
  lifecycle: production
  owner: team-c
  system: petstore
  definition:
    $text: https://dev.azure.com/rtl-nl/RTL%20Shared/_git/documentation?path=%2Fopenapi.yaml