apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  # This is an extra long description
  description: The Petstore is an example API used to show features of the OpenAPI spec.
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-api
  description: Retrieve petstore details
spec:
  type: openapi
  lifecycle: production
  owner: team-c
  system: petstore
  definition:
    $text: ./openapi.yaml    